####1

In [ ]:
## install required packages
!pip install swig
!pip install wrds
!pip install pyportfolioopt
## install finrl library
!pip install git+https://github.com/AI4Finance-Foundation/FinRL.git

Collecting swig
  Downloading swig-4.2.1-py2.py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 7.3 MB/s eta 0:00:00
Installing collected packages: swig
Successfully installed swig-4.2.1
Collecting wrds
  Downloading wrds-3.2.0-py3-none-any.whl (13 kB)
Collecting numpy<1.27,>=1.26 (from wrds)
  Downloading numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 56.0 MB/s eta 0:00:00
Collecting packaging<23.3 (from wrds)
  Downloading packaging-23.2-py3-none-any.whl (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.0/53.0 kB 6.4 MB/s eta 0:00:00
Collecting pandas<2.3,>=2.2 (from wrds)
  Downloading pandas-2.2.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.0/13.0 MB 65.8 MB/s eta 0:00:00
Collecting psycopg2-binary<2.10,>=2.9 (from wrds)
  Downloading psycopg2_binary-2.9.9-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 78.6 MB/s eta 0:00:00
Collecting scipy<1.13,>=1.12 (from wrds)
  Downloading scipy-1.12.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.4/38.4 MB 11.3 MB/s eta 0:00:00
Requirement already satisfied: sqlalchemy<2.1,>=2 in /usr/local/lib/python3.10/dist-packages (from wrds) (2.0.31)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas<2.3,>=2.2->wrds) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<2.3,>=2.2->wrds) (2023.4)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas<2.3,>=2.2->wrds) (2024.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy<2.1,>=2->wrds) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy<2.1,>=2->wrds) (3.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas<2.3,>=2.2->wrds) (1.16.0)
Installing collected packages: psycopg2-binary, packaging, numpy, scipy, pandas, wrds
  Attempting uninstall: packaging
    Found existing installation: packaging 24.1
    Uninstalling packaging-24.1:
      Successfully uninstalled packaging-24.1
  Attempting uninstall: numpy
    Found existing installation: numpy 1.25.2
    Uninstalling numpy-1.25.2:
      Successfully uninstalled numpy-1.25.2
  Attempting uninstall: scipy
    Found existing installation: scipy 1.11.4
    Uninstalling scipy-1.11.4:
      Successfully uninstalled scipy-1.11.4
  Attempting uninstall: pandas
    Found existing installation: pandas 2.0.3
    Uninstalling pandas-2.0.3:
      Successfully uninstalled pandas-2.0.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cudf-cu12 24.4.1 requires pandas<2.2.2dev0,>=2.0, but you have pandas 2.2.2 which is incompatible.
google-colab 1.0.0 requires pandas==2.0.3, but you have pandas 2.2.2 which is incompatible.
Successfully installed numpy-1.26.4 packaging-23.2 pandas-2.2.2 psycopg2-binary-2.9.9 scipy-1.12.0 wrds-3.2.0
Collecting pyportfolioopt
  Downloading pyportfolioopt-1.5.5-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.9/61.9 kB 1.6 MB/s eta 0:00:00
Requirement already satisfied: cvxpy<2.0.0,>=1.1.19 in /usr/local/lib/python3.10/dist-packages (from pyportfolioopt) (1.3.4)
Requirement already satisfied: numpy<2.0.0,>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pyportfolioopt) (1.26.4)
Requirement already satisfied: pandas>=0.19 in /usr/local/lib/python3.10/dist-packages (from pyportfolioopt) (2.2.2)
Requirement already satisfied: scipy<2.0,>=1.3 in /usr/local/lib/python3.10/dist-packages (from pyportfolioopt) (1.12.0)
Requirement already satisfied: osqp>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from cvxpy<2.0.0,>=1.1.19->pyportfolioopt) (0.6.2.post8)
Requirement already satisfied: ecos>=2 in /usr/local/lib/python3.10/dist-packages (from cvxpy<2.0.0,>=1.1.19->pyportfolioopt) (2.0.14)
Requirement already satisfied: scs>=1.1.6 in /usr/local/lib/python3.10/dist-packages (from cvxpy<2.0.0,>=1.1.19->pyportfolioopt) (3.2.6)
Requirement already satisfied: setuptools>65.5.1 in /usr/local/lib/python3.10/dist-packages (from cvxpy<2.0.0,>=1.1.19->pyportfolioopt) (67.7.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.19->pyportfolioopt) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.19->pyportfolioopt) (2023.4)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.19->pyportfolioopt) (2024.1)
Requirement already satisfied: qdldl in /usr/local/lib/python3.10/dist-packages (from osqp>=0.4.1->cvxpy<2.0.0,>=1.1.19->pyportfolioopt) (0.1.7.post4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas>=0.19->pyportfolioopt) (1.16.0)
Installing collected packages: pyportfolioopt
Successfully installed pyportfolioopt-1.5.5
Collecting git+https://github.com/AI4Finance-Foundation/FinRL.git
  Cloning https://github.com/AI4Finance-Foundation/FinRL.git to /tmp/pip-req-build-t_kxna8v
  Running command git clone --filter=blob:none --quiet https://github.com/AI4Finance-Foundation/FinRL.git /tmp/pip-req-build-t_kxna8v
  Resolved https://github.com/AI4Finance-Foundation/FinRL.git to commit c3364c895896a09c51dac4bade6965b97be3776e
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting elegantrl@ git+https://github.com/AI4Finance-Foundation/ElegantRL.git#egg=elegantrl (from finrl==0.3.6)
  Cloning https://github.com/AI4Finance-Foundation/ElegantRL.git to /tmp/pip-install-rknnj_op/elegantrl_563d8b8624d442a29b6ced39aa0c9882
  Running command git clone --filter=blob:none --quiet https://github.com/AI4Finance-Foundation/ElegantRL.git /tmp/pip-install-rknnj_op/elegantrl_563d8b8624d442a29b6ced39aa0c9882
  Resolved https://github.com/AI4Finance-Foundation/ElegantRL.git to commit 5350d0cd9d0a0fba0b65d124d4a5c53cd7890890
  Preparing metadata (setup.py) ... done
Collecting alpaca-trade-api<4,>=3 (from finrl==0.3.6)
  Downloading alpaca_trade_api-3.2.0-py3-none-any.whl (34 kB)
Collecting ccxt<4,>=3 (from finrl==0.3.6)
  Downloading ccxt-3.1.60-py2.py3-none-any.whl (4.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 9.8 MB/s eta 0:00:00
Collecting exchange-calendars<5,>=4 (from finrl==0.3.6)
  Downloading exchange_calendars-4.5.5-py3-none-any.whl (196 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.1/196.1 kB 18.1 MB/s eta 0:00:00
Collecting jqdatasdk<2,>=1 (from finrl==0.3.6)
  Downloading jqdatasdk-1.9.5-py3-none-any.whl (76 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.5/76.5 kB 8.4 MB/s eta 0:00:00
Collecting pyfolio<0.10,>=0.9 (from finrl==0.3.6)
  Downloading pyfolio-0.9.2.tar.gz (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.1/91.1 kB 10.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pyportfolioopt<2,>=1 in /usr/local/lib/python3.10/dist-packages (from finrl==0.3.6) (1.5.5)
Collecting ray[default,tune]<3,>=2 (from finrl==0.3.6)
  Downloading ray-2.32.0-cp310-cp310-manylinux2014_x86_64.whl (65.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.7/65.7 MB 8.9 MB/s eta 0:00:00
Requirement already satisfied: scikit-learn<2,>=1 in /usr/local/lib/python3.10/dist-packages (from finrl==0.3.6) (1.2.2)
Collecting stable-baselines3[extra]>=2.0.0a5 (from finrl==0.3.6)
  Downloading stable_baselines3-2.4.0a4-py3-none-any.whl (182 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 182.3/182.3 kB 17.9 MB/s eta 0:00:00
Collecting stockstats<0.6,>=0.5 (from finrl==0.3.6)
  Downloading stockstats-0.5.4-py2.py3-none-any.whl (21 kB)
Requirement already satisfied: wrds<4,>=3 in /usr/local/lib/python3.10/dist-packages (from finrl==0.3.6) (3.2.0)
Requirement already satisfied: yfinance<0.3,>=0.2 in /usr/local/lib/python3.10/dist-packages (from finrl==0.3.6) (0.2.40)
Requirement already satisfied: pandas>=0.18.1 in /usr/local/lib/python3.10/dist-packages (from alpaca-trade-api<4,>=3->finrl==0.3.6) (2.2.2)
Requirement already satisfied: numpy>=1.11.1 in /usr/local/lib/python3.10/dist-packages (from alpaca-trade-api<4,>=3->finrl==0.3.6) (1.26.4)
Requirement already satisfied: requests<3,>2 in /usr/local/lib/python3.10/dist-packages (from alpaca-trade-api<4,>=3->finrl==0.3.6) (2.31.0)
Collecting urllib3<2,>1.24 (from alpaca-trade-api<4,>=3->finrl==0.3.6)
  Downloading urllib3-1.26.19-py2.py3-none-any.whl (143 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.9/143.9 kB 16.8 MB/s eta 0:00:00
Requirement already satisfied: websocket-client<2,>=0.56.0 in /usr/local/lib/python3.10/dist-packages (from alpaca-trade-api<4,>=3->finrl==0.3.6) (1.8.0)
Collecting websockets<11,>=9.0 (from alpaca-trade-api<4,>=3->finrl==0.3.6)
  Downloading websockets-10.4-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (106 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.8/106.8 kB 12.9 MB/s eta 0:00:00
Collecting msgpack==1.0.3 (from alpaca-trade-api<4,>=3->finrl==0.3.6)
  Downloading msgpack-1.0.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (323 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 323.7/323.7 kB 31.0 MB/s eta 0:00:00
Requirement already satisfied: aiohttp<4,>=3.8.3 in /usr/local/lib/python3.10/dist-packages (from alpaca-trade-api<4,>=3->finrl==0.3.6) (3.9.5)
Requirement already satisfied: PyYAML==6.0.1 in /usr/local/lib/python3.10/dist-packages (from alpaca-trade-api<4,>=3->finrl==0.3.6) (6.0.1)
Collecting deprecation==2.1.0 (from alpaca-trade-api<4,>=3->finrl==0.3.6)
  Downloading deprecation-2.1.0-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from deprecation==2.1.0->alpaca-trade-api<4,>=3->finrl==0.3.6) (23.2)
Requirement already satisfied: setuptools>=60.9.0 in /usr/local/lib/python3.10/dist-packages (from ccxt<4,>=3->finrl==0.3.6) (67.7.2)
Requirement already satisfied: certifi>=2018.1.18 in /usr/local/lib/python3.10/dist-packages (from ccxt<4,>=3->finrl==0.3.6) (2024.7.4)
Requirement already satisfied: cryptography>=2.6.1 in /usr/local/lib/python3.10/dist-packages (from ccxt<4,>=3->finrl==0.3.6) (42.0.8)
Collecting aiodns>=1.1.1 (from ccxt<4,>=3->finrl==0.3.6)
  Downloading aiodns-3.2.0-py3-none-any.whl (5.7 kB)
Requirement already satisfied: yarl>=1.7.2 in /usr/local/lib/python3.10/dist-packages (from ccxt<4,>=3->finrl==0.3.6) (1.9.4)
Collecting pyluach (from exchange-calendars<5,>=4->finrl==0.3.6)
  Downloading pyluach-2.2.0-py3-none-any.whl (25 kB)
Requirement already satisfied: toolz in /usr/local/lib/python3.10/dist-packages (from exchange-calendars<5,>=4->finrl==0.3.6) (0.12.1)
Requirement already satisfied: tzdata in /usr/local/lib/python3.10/dist-packages (from exchange-calendars<5,>=4->finrl==0.3.6) (2024.1)
Collecting korean-lunar-calendar (from exchange-calendars<5,>=4->finrl==0.3.6)
  Downloading korean_lunar_calendar-0.3.1-py3-none-any.whl (9.0 kB)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from jqdatasdk<2,>=1->finrl==0.3.6) (1.16.0)
Requirement already satisfied: SQLAlchemy>=1.2.8 in /usr/local/lib/python3.10/dist-packages (from jqdatasdk<2,>=1->finrl==0.3.6) (2.0.31)
Collecting pymysql>=0.7.6 (from jqdatasdk<2,>=1->finrl==0.3.6)
  Downloading PyMySQL-1.1.1-py3-none-any.whl (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.0/45.0 kB 5.1 MB/s eta 0:00:00
Collecting thriftpy2>=0.3.9 (from jqdatasdk<2,>=1->finrl==0.3.6)
  Downloading thriftpy2-0.5.2.tar.gz (782 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 782.3/782.3 kB 52.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: ipython>=3.2.3 in /usr/local/lib/python3.10/dist-packages (from pyfolio<0.10,>=0.9->finrl==0.3.6) (7.34.0)
Requirement already satisfied: matplotlib>=1.4.0 in /usr/local/lib/python3.10/dist-packages (from pyfolio<0.10,>=0.9->finrl==0.3.6) (3.7.1)
Requirement already satisfied: pytz>=2014.10 in /usr/local/lib/python3.10/dist-packages (from pyfolio<0.10,>=0.9->finrl==0.3.6) (2023.4)
Requirement already satisfied: scipy>=0.14.0 in /usr/local/lib/python3.10/dist-packages (from pyfolio<0.10,>=0.9->finrl==0.3.6) (1.12.0)
Requirement already satisfied: seaborn>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from pyfolio<0.10,>=0.9->finrl==0.3.6) (0.13.1)
Collecting empyrical>=0.5.0 (from pyfolio<0.10,>=0.9->finrl==0.3.6)
  Downloading empyrical-0.5.5.tar.gz (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.8/52.8 kB 6.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: cvxpy<2.0.0,>=1.1.19 in /usr/local/lib/python3.10/dist-packages (from pyportfolioopt<2,>=1->finrl==0.3.6) (1.3.4)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.10/dist-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (8.1.7)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (3.15.4)
Requirement already satisfied: jsonschema in /usr/local/lib/python3.10/dist-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (4.19.2)
Requirement already satisfied: protobuf!=3.19.5,>=3.15.3 in /usr/local/lib/python3.10/dist-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (3.20.3)
Requirement already satisfied: aiosignal in /usr/local/lib/python3.10/dist-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (1.3.1)
Requirement already satisfied: frozenlist in /usr/local/lib/python3.10/dist-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (1.4.1)
Collecting tensorboardX>=1.9 (from ray[default,tune]<3,>=2->finrl==0.3.6)
  Downloading tensorboardX-2.6.2.2-py2.py3-none-any.whl (101 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.7/101.7 kB 11.6 MB/s eta 0:00:00
Requirement already satisfied: pyarrow>=6.0.1 in /usr/local/lib/python3.10/dist-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (14.0.2)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (2023.6.0)
Collecting aiohttp-cors (from ray[default,tune]<3,>=2->finrl==0.3.6)
  Downloading aiohttp_cors-0.7.0-py3-none-any.whl (27 kB)
Collecting colorful (from ray[default,tune]<3,>=2->finrl==0.3.6)
  Downloading colorful-0.5.6-py2.py3-none-any.whl (201 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 201.4/201.4 kB 21.5 MB/s eta 0:00:00
Collecting py-spy>=0.2.0 (from ray[default,tune]<3,>=2->finrl==0.3.6)
  Downloading py_spy-0.3.14-py2.py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.whl (3.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 65.8 MB/s eta 0:00:00
Collecting opencensus (from ray[default,tune]<3,>=2->finrl==0.3.6)
  Downloading opencensus-0.11.4-py2.py3-none-any.whl (128 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.2/128.2 kB 14.1 MB/s eta 0:00:00
Requirement already satisfied: pydantic!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,<3 in /usr/local/lib/python3.10/dist-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (2.8.2)
Requirement already satisfied: prometheus-client>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (0.20.0)
Requirement already satisfied: smart-open in /usr/local/lib/python3.10/dist-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (7.0.4)
Collecting virtualenv!=20.21.1,>=20.0.24 (from ray[default,tune]<3,>=2->finrl==0.3.6)
  Downloading virtualenv-20.26.3-py3-none-any.whl (5.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 76.1 MB/s eta 0:00:00
Requirement already satisfied: grpcio>=1.42.0 in /usr/local/lib/python3.10/dist-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (1.64.1)
Collecting memray (from ray[default,tune]<3,>=2->finrl==0.3.6)
  Downloading memray-1.13.4-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (6.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.4/6.4 MB 83.3 MB/s eta 0:00:00
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn<2,>=1->finrl==0.3.6) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn<2,>=1->finrl==0.3.6) (3.5.0)
Collecting gymnasium<0.30,>=0.28.1 (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6)
  Downloading gymnasium-0.29.1-py3-none-any.whl (953 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 953.9/953.9 kB 47.8 MB/s eta 0:00:00
Requirement already satisfied: torch>=1.13 in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (2.3.1+cu121)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (2.2.1)
Requirement already satisfied: opencv-python in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (4.8.0.76)
Requirement already satisfied: pygame in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (2.6.0)
Requirement already satisfied: tensorboard>=2.9.1 in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (2.15.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (5.9.5)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (4.66.4)
Requirement already satisfied: rich in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (13.7.1)
Collecting shimmy[atari]~=1.3.0 (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6)
  Downloading Shimmy-1.3.0-py3-none-any.whl (37 kB)
Requirement already satisfied: pillow in /usr/local/lib/python3.10/dist-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (9.4.0)
Collecting autorom[accept-rom-license]~=0.6.1 (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6)
  Downloading AutoROM-0.6.1-py3-none-any.whl (9.4 kB)
Requirement already satisfied: psycopg2-binary<2.10,>=2.9 in /usr/local/lib/python3.10/dist-packages (from wrds<4,>=3->finrl==0.3.6) (2.9.9)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.10/dist-packages (from yfinance<0.3,>=0.2->finrl==0.3.6) (0.0.11)
Requirement already satisfied: lxml>=4.9.1 in /usr/local/lib/python3.10/dist-packages (from yfinance<0.3,>=0.2->finrl==0.3.6) (4.9.4)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from yfinance<0.3,>=0.2->finrl==0.3.6) (4.2.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.10/dist-packages (from yfinance<0.3,>=0.2->finrl==0.3.6) (2.4.4)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.10/dist-packages (from yfinance<0.3,>=0.2->finrl==0.3.6) (3.17.6)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.10/dist-packages (from yfinance<0.3,>=0.2->finrl==0.3.6) (4.12.3)
Requirement already satisfied: html5lib>=1.1 in /usr/local/lib/python3.10/dist-packages (from yfinance<0.3,>=0.2->finrl==0.3.6) (1.1)

# Preprocess Data

In [ ]:
import pandas as pd
import numpy as np
import datetime
import yfinance as yf

from finrl.meta.preprocessor.yahoodownloader import YahooDownloader
from finrl.meta.preprocessor.preprocessors import FeatureEngineer, data_split
from finrl import config_tickers
from finrl.config import INDICATORS

import itertools

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
TRAIN_START_DATE = '2009-01-01'
TRAIN_END_DATE = '2022-01-01'
TRADE_START_DATE = '2022-01-02'
TRADE_END_DATE = '2024-06-01'
symbols = [
            'AAPL',
            'MSFT',
            'AMZN',
            'NVDA',
            'AMD'
            ]

df = YahooDownloader(start_date = TRAIN_START_DATE,
                                end_date = TRADE_END_DATE,
                                ticker_list = symbols).fetch_data()

df.head(2)

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed

Shape of DataFrame:  (19395, 8)

         date      open      high       low     close     volume   tic  day
0  2009-01-02  3.067143  3.251429  3.041429  2.740172  746015200  AAPL    4
1  2009-01-02  2.190000  2.430000  2.170000  2.380000   13832100   AMD    4

In [ ]:
INDICATORS = ['macd',
               'rsi',
               'cci',
               'dx']

fe = FeatureEngineer(use_technical_indicator=True,
                     tech_indicator_list = INDICATORS,
                     use_vix=False,
                     use_turbulence=True,
                     user_defined_feature = False)

processed = fe.preprocess_data(df)

processed = processed.drop(columns=['open','high','low','volume','day'])

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

Successfully added technical indicators
Successfully added turbulence index

In [ ]:
list_ticker = processed["tic"].unique().tolist()
list_date = list(pd.date_range(processed['date'].min(),processed['date'].max()).astype(str))
combination = list(itertools.product(list_date,list_ticker))

processed_full = pd.DataFrame(combination,columns=["date","tic"]).merge(processed,on=["date","tic"],how="left")
processed_full = processed_full[processed_full['date'].isin(processed['date'])]
processed_full = processed_full.sort_values(['date','tic'])

processed_full = processed_full.fillna(0)

,date,tic,close,macd,rsi,cci,dx,turbulence
0,2009-01-02,AAPL,2.740172,0.000000,100.000000,66.666667,100.000000,0.000000
1,2009-01-02,AMD,2.380000,0.000000,100.000000,66.666667,100.000000,0.000000
2,2009-01-02,AMZN,2.718000,0.000000,100.000000,66.666667,100.000000,0.000000
3,2009-01-02,MSFT,15.011640,0.000000,100.000000,66.666667,100.000000,0.000000
4,2009-01-02,NVDA,0.199726,0.000000,100.000000,66.666667,100.000000,0.000000
...,...,...,...,...,...,...,...,...
28140,2024-05-31,AAPL,192.250000,4.254256,67.294615,83.902344,18.866838,2.059761
28141,2024-05-31,AMD,166.899994,1.943916,55.488332,38.653476,4.728638,2.059761
28142,2024-05-31,AMZN,176.440002,-0.715091,36.745153,-201.650314,46.940153,2.059761
28143,2024-05-31,MSFT,415.130005,3.323865,46.929727,-134.029450,50.967552,2.059761
28144,2024-05-31,NVDA,109.624001,6.296193,68.771273,79.139023,43.235332,2.059761

In [ ]:
# Split the data
train = data_split(processed_full, TRAIN_START_DATE,TRAIN_END_DATE)
trade = data_split(processed_full, TRADE_START_DATE,TRADE_END_DATE)
print(len(train))
print(len(trade))

trade_path= '/content/drive/MyDrive/DRLP/trade.csv'
train_path = '/content/drive/MyDrive/DRLP/train.csv'

with open(train_path, 'w', encoding='utf-8-sig') as f:
    train.to_csv(f)

with open(trade_path, 'w', encoding = 'utf-8-sig') as f:
  trade.to_csv(f)

16365
3030

# Load the Data from and train the model

#### install RecurrentPPO

In [ ]:
!git clone https://github.com/DLR-RM/rl-baselines3-zoo
%cd rl-baselines3-zoo
!pip install -e .
"""!apt-get install swig cmake ffmpeg
!pip install -r requirements.txt
!pip install -e .[plots,tests]"""

fatal: destination path 'rl-baselines3-zoo' already exists and is not an empty directory.
/content/rl-baselines3-zoo
Obtaining file:///content/rl-baselines3-zoo
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting sb3-contrib<3.0,>=2.4.0a4 (from rl_zoo3==2.4.0a4)
  Downloading sb3_contrib-2.4.0a4-py3-none-any.whl (80 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.2/80.2 kB 2.1 MB/s eta 0:00:00
Requirement already satisfied: gymnasium~=0.29.1 in /usr/local/lib/python3.10/dist-packages (from rl_zoo3==2.4.0a4) (0.29.1)
Collecting huggingface-sb3<4.0,>=3.0 (from rl_zoo3==2.4.0a4)
  Downloading huggingface_sb3-3.0-py3-none-any.whl (9.7 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from rl_zoo3==2.4.0a4) (4.66.4)
Requirement already satisfied: rich in /usr/local/lib/python3.10/dist-packages (from rl_zoo3==2.4.0a4) (13.7.1)
Collecting optuna>=3.0 (from rl_zoo3==2.4.0a4)
  Downloading optuna-3.6.1-py3-none-any.whl (380 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 380.1/380.1 kB 12.3 MB/s eta 0:00:00
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from rl_zoo3==2.4.0a4) (6.0.1)
Collecting pytablewriter~=1.2 (from rl_zoo3==2.4.0a4)
  Downloading pytablewriter-1.2.0-py3-none-any.whl (111 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 111.1/111.1 kB 10.7 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from gymnasium~=0.29.1->rl_zoo3==2.4.0a4) (1.26.4)
Requirement already satisfied: cloudpickle>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from gymnasium~=0.29.1->rl_zoo3==2.4.0a4) (2.2.1)
Requirement already satisfied: typing-extensions>=4.3.0 in /usr/local/lib/python3.10/dist-packages (from gymnasium~=0.29.1->rl_zoo3==2.4.0a4) (4.12.2)
Requirement already satisfied: farama-notifications>=0.0.1 in /usr/local/lib/python3.10/dist-packages (from gymnasium~=0.29.1->rl_zoo3==2.4.0a4) (0.0.4)
Requirement already satisfied: huggingface-hub~=0.8 in /usr/local/lib/python3.10/dist-packages (from huggingface-sb3<4.0,>=3.0->rl_zoo3==2.4.0a4) (0.23.5)
Requirement already satisfied: wasabi in /usr/local/lib/python3.10/dist-packages (from huggingface-sb3<4.0,>=3.0->rl_zoo3==2.4.0a4) (1.1.3)
Collecting alembic>=1.5.0 (from optuna>=3.0->rl_zoo3==2.4.0a4)
  Downloading alembic-1.13.2-py3-none-any.whl (232 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.0/233.0 kB 23.1 MB/s eta 0:00:00
Collecting colorlog (from optuna>=3.0->rl_zoo3==2.4.0a4)
  Downloading colorlog-6.8.2-py3-none-any.whl (11 kB)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from optuna>=3.0->rl_zoo3==2.4.0a4) (23.2)
Requirement already satisfied: sqlalchemy>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from optuna>=3.0->rl_zoo3==2.4.0a4) (2.0.31)
Requirement already satisfied: setuptools>=38.3.0 in /usr/local/lib/python3.10/dist-packages (from pytablewriter~=1.2->rl_zoo3==2.4.0a4) (67.7.2)
Collecting DataProperty<2,>=1.0.1 (from pytablewriter~=1.2->rl_zoo3==2.4.0a4)
  Downloading DataProperty-1.0.1-py3-none-any.whl (27 kB)
Collecting mbstrdecoder<2,>=1.0.0 (from pytablewriter~=1.2->rl_zoo3==2.4.0a4)
  Downloading mbstrdecoder-1.1.3-py3-none-any.whl (7.8 kB)
Collecting pathvalidate<4,>=2.3.0 (from pytablewriter~=1.2->rl_zoo3==2.4.0a4)
  Downloading pathvalidate-3.2.0-py3-none-any.whl (23 kB)
Collecting tabledata<2,>=1.3.1 (from pytablewriter~=1.2->rl_zoo3==2.4.0a4)
  Downloading tabledata-1.3.3-py3-none-any.whl (11 kB)
Collecting tcolorpy<1,>=0.0.5 (from pytablewriter~=1.2->rl_zoo3==2.4.0a4)
  Downloading tcolorpy-0.1.6-py3-none-any.whl (8.1 kB)
Collecting typepy[datetime]<2,>=1.3.2 (from pytablewriter~=1.2->rl_zoo3==2.4.0a4)
  Downloading typepy-1.3.2-py3-none-any.whl (31 kB)
Requirement already satisfied: stable-baselines3<3.0,>=2.4.0a4 in /usr/local/lib/python3.10/dist-packages (from sb3-contrib<3.0,>=2.4.0a4->rl_zoo3==2.4.0a4) (2.4.0a4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich->rl_zoo3==2.4.0a4) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich->rl_zoo3==2.4.0a4) (2.16.1)
Collecting Mako (from alembic>=1.5.0->optuna>=3.0->rl_zoo3==2.4.0a4)
  Downloading Mako-1.3.5-py3-none-any.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.6/78.6 kB 9.3 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub~=0.8->huggingface-sb3<4.0,>=3.0->rl_zoo3==2.4.0a4) (3.15.4)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub~=0.8->huggingface-sb3<4.0,>=3.0->rl_zoo3==2.4.0a4) (2023.6.0)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub~=0.8->huggingface-sb3<4.0,>=3.0->rl_zoo3==2.4.0a4) (2.31.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich->rl_zoo3==2.4.0a4) (0.1.2)
Requirement already satisfied: chardet<6,>=3.0.4 in /usr/local/lib/python3.10/dist-packages (from mbstrdecoder<2,>=1.0.0->pytablewriter~=1.2->rl_zoo3==2.4.0a4) (5.2.0)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy>=1.3.0->optuna>=3.0->rl_zoo3==2.4.0a4) (3.0.3)
Requirement already satisfied: torch>=1.13 in /usr/local/lib/python3.10/dist-packages (from stable-baselines3<3.0,>=2.4.0a4->sb3-contrib<3.0,>=2.4.0a4->rl_zoo3==2.4.0a4) (2.3.1+cu121)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from stable-baselines3<3.0,>=2.4.0a4->sb3-contrib<3.0,>=2.4.0a4->rl_zoo3==2.4.0a4) (2.2.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from stable-baselines3<3.0,>=2.4.0a4->sb3-contrib<3.0,>=2.4.0a4->rl_zoo3==2.4.0a4) (3.7.1)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.0 in /usr/local/lib/python3.10/dist-packages (from typepy[datetime]<2,>=1.3.2->pytablewriter~=1.2->rl_zoo3==2.4.0a4) (2.8.2)
Requirement already satisfied: pytz>=2018.9 in /usr/local/lib/python3.10/dist-packages (from typepy[datetime]<2,>=1.3.2->pytablewriter~=1.2->rl_zoo3==2.4.0a4) (2023.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil<3.0.0,>=2.8.0->typepy[datetime]<2,>=1.3.2->pytablewriter~=1.2->rl_zoo3==2.4.0a4) (1.16.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.13->stable-baselines3<3.0,>=2.4.0a4->sb3-contrib<3.0,>=2.4.0a4->rl_zoo3==2.4.0a4) (1.13.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.13->stable-baselines3<3.0,>=2.4.0a4->sb3-contrib<3.0,>=2.4.0a4->rl_zoo3==2.4.0a4) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.13->stable-baselines3<3.0,>=2.4.0a4->sb3-contrib<3.0,>=2.4.0a4->rl_zoo3==2.4.0a4) (3.1.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch>=1.13->stable-baselines3<3.0,>=2.4.0a4->sb3-contrib<3.0,>=2.4.0a4->rl_zoo3==2.4.0a4) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch>=1.13->stable-baselines3<3.0,>=2.4.0a4->sb3-contrib<3.0,>=2.4.0a4->rl_zoo3==2.4.0a4) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch>=1.13->stable-baselines3<3.0,>=2.4.0a4->sb3-contrib<3.0,>=2.4.0a4->rl_zoo3==2.4.0a4) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /usr/local/lib/python3.10/dist-packages (from torch>=1.13->stable-baselines3<3.0,>=2.4.0a4->sb3-contrib<3.0,>=2.4.0a4->rl_zoo3==2.4.0a4) (8.9.2.26)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /usr/local/lib/python3.10/dist-packages (from torch>=1.13->stable-baselines3<3.0,>=2.4.0a4->sb3-contrib<3.0,>=2.4.0a4->rl_zoo3==2.4.0a4) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /usr/local/lib/python3.10/dist-packages (from torch>=1.13->stable-baselines3<3.0,>=2.4.0a4->sb3-contrib<3.0,>=2.4.0a4->rl_zoo3==2.4.0a4) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /usr/local/lib/python3.10/dist-packages (from torch>=1.13->stable-baselines3<3.0,>=2.4.0a4->sb3-contrib<3.0,>=2.4.0a4->rl_zoo3==2.4.0a4) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /usr/local/lib/python3.10/dist-packages (from torch>=1.13->stable-baselines3<3.0,>=2.4.0a4->sb3-contrib<3.0,>=2.4.0a4->rl_zoo3==2.4.0a4) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /usr/local/lib/python3.10/dist-packages (from torch>=1.13->stable-baselines3<3.0,>=2.4.0a4->sb3-contrib<3.0,>=2.4.0a4->rl_zoo3==2.4.0a4) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.20.5 in /usr/local/lib/python3.10/dist-packages (from torch>=1.13->stable-baselines3<3.0,>=2.4.0a4->sb3-contrib<3.0,>=2.4.0a4->rl_zoo3==2.4.0a4) (2.20.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch>=1.13->stable-baselines3<3.0,>=2.4.0a4->sb3-contrib<3.0,>=2.4.0a4->rl_zoo3==2.4.0a4) (12.1.105)
Requirement already satisfied: triton==2.3.1 in /usr/local/lib/python3.10/dist-packages (from torch>=1.13->stable-baselines3<3.0,>=2.4.0a4->sb3-contrib<3.0,>=2.4.0a4->rl_zoo3==2.4.0a4) (2.3.1)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.10/dist-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.13->stable-baselines3<3.0,>=2.4.0a4->sb3-contrib<3.0,>=2.4.0a4->rl_zoo3==2.4.0a4) (12.5.82)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.10/dist-packages (from Mako->alembic>=1.5.0->optuna>=3.0->rl_zoo3==2.4.0a4) (2.1.5)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->stable-baselines3<3.0,>=2.4.0a4->sb3-contrib<3.0,>=2.4.0a4->rl_zoo3==2.4.0a4) (1.2.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->stable-baselines3<3.0,>=2.4.0a4->sb3-contrib<3.0,>=2.4.0a4->rl_zoo3==2.4.0a4) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->stable-baselines3<3.0,>=2.4.0a4->sb3-contrib<3.0,>=2.4.0a4->rl_zoo3==2.4.0a4) (4.53.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->stable-baselines3<3.0,>=2.4.0a4->sb3-contrib<3.0,>=2.4.0a4->rl_zoo3==2.4.0a4) (1.4.5)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->stable-baselines3<3.0,>=2.4.0a4->sb3-contrib<3.0,>=2.4.0a4->rl_zoo3==2.4.0a4) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->stable-baselines3<3.0,>=2.4.0a4->sb3-contrib<3.0,>=2.4.0a4->rl_zoo3==2.4.0a4) (3.1.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->stable-baselines3<3.0,>=2.4.0a4->sb3-contrib<3.0,>=2.4.0a4->rl_zoo3==2.4.0a4) (2024.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub~=0.8->huggingface-sb3<4.0,>=3.0->rl_zoo3==2.4.0a4) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub~=0.8->huggingface-sb3<4.0,>=3.0->rl_zoo3==2.4.0a4) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub~=0.8->huggingface-sb3<4.0,>=3.0->rl_zoo3==2.4.0a4) (1.26.19)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub~=0.8->huggingface-sb3<4.0,>=3.0->rl_zoo3==2.4.0a4) (2024.7.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.13->stable-baselines3<3.0,>=2.4.0a4->sb3-contrib<3.0,>=2.4.0a4->rl_zoo3==2.4.0a4) (1.3.0)
Building wheels for collected packages: rl_zoo3
  Building editable for rl_zoo3 (pyproject.toml) ... done
  Created wheel for rl_zoo3: filename=rl_zoo3-2.4.0a4-0.editable-py3-none-any.whl size=4368 sha256=c229c60a389d7965cb90197343acd1bbe78fa3dd8587c1cce80e7f29656beff3
  Stored in directory: /tmp/pip-ephem-wheel-cache-nfzfl5f2/wheels/27/09/4c/4de875547836f3bdb7479fe076761dbc83b5661ef4acb0c858
Successfully built rl_zoo3
Installing collected packages: tcolorpy, pathvalidate, mbstrdecoder, Mako, colorlog, typepy, alembic, optuna, huggingface-sb3, DataProperty, tabledata, sb3-contrib, pytablewriter, rl_zoo3
Successfully installed DataProperty-1.0.1 Mako-1.3.5 alembic-1.13.2 colorlog-6.8.2 huggingface-sb3-3.0 mbstrdecoder-1.1.3 optuna-3.6.1 pathvalidate-3.2.0 pytablewriter-1.2.0 rl_zoo3-2.4.0a4 sb3-contrib-2.4.0a4 tabledata-1.3.3 tcolorpy-0.1.6 typepy-1.3.2

'!apt-get install swig cmake ffmpeg\n!pip install -r requirements.txt\n!pip install -e .[plots,tests]'

## Setup Environment and model

#### imports

In [ ]:
import os
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
from stable_baselines3.common.torch_layers import BaseFeaturesExtractor
from sb3_contrib import RecurrentPPO
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy
from finrl.meta.env_stock_trading.env_stocktrading import StockTradingEnv
from finrl.agents.stablebaselines3.models import DRLAgent
from finrl import config_tickers
from finrl.main import check_and_make_directories
from finrl.config import INDICATORS, TRAINED_MODEL_DIR, RESULTS_DIR
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

#### env

In [ ]:

# Directory to save trained models and evaluation results
model_dir = "/content/drive/MyDrive/DRLP/Result"
check_and_make_directories([model_dir])

# Load the train and trade datasets
train = pd.read_csv('/content/drive/MyDrive/DRLP/train.csv')
train = train.set_index(train.columns[0])
train.index.names = ['']

trade = pd.read_csv('/content/drive/MyDrive/DRLP/trade.csv')
trade = trade.set_index(trade.columns[0])
trade.index.names = ['']

INDICATORS = ['macd', 'rsi', 'cci', 'dx']
stock_dimension = len(train.tic.unique())
state_space = 1 + 2 * stock_dimension + len(INDICATORS) * stock_dimension

# Extract turbulence values from the train dataset
turbulence_data = train[['date', 'turbulence']].drop_duplicates()
turbulence_values = turbulence_data['turbulence'].values

# Calculate the 90th percentile threshold
turbulence_threshold = np.percentile(turbulence_values, 90)

buy_cost_list = sell_cost_list = [0.001] * stock_dimension
num_stock_shares = [0] * stock_dimension

env_kwargs = {
    "hmax": 100,
    "initial_amount": 1000000,
    "num_stock_shares": num_stock_shares,
    "buy_cost_pct": buy_cost_list,
    "sell_cost_pct": sell_cost_list,
    "state_space": state_space,
    "stock_dim": stock_dimension,
    "tech_indicator_list": INDICATORS,
    "action_space": stock_dimension,
    "reward_scaling": 1e-4,
    "turbulence_threshold": turbulence_threshold
}

from gymnasium import Wrapper
from collections import deque


from gymnasium.spaces import Box
import gymnasium as gym

class StockTradingEnvWrapper(Wrapper):
    def __init__(self, env, window_size=10):
        super(StockTradingEnvWrapper, self).__init__(env)
        self.window_size = window_size
        self.observation_window = deque(maxlen=window_size)
        self.portfolio_values = []

        # Define the observation space to match the windowed observations
        single_obs_shape = env.observation_space.shape
        self.observation_space = Box(
            low=np.repeat(env.observation_space.low[np.newaxis, :], window_size, axis=0),
            high=np.repeat(env.observation_space.high[np.newaxis, :], window_size, axis=0),
            dtype=env.observation_space.dtype
        )

    def step(self, action):
        state, reward, done, truncated, info = self.env.step(action)
        state = state[0]  # Only use the list of values from the state tuple

        self.observation_window.append(state)
        if len(self.observation_window) < self.window_size:
            padded_state = [self.observation_window[0]] * (self.window_size - len(self.observation_window)) + list(self.observation_window)
        else:
            padded_state = list(self.observation_window)

        portfolio_value = self._calculate_portfolio_value()
        self.portfolio_values.append(portfolio_value)

        if done:
            info['portfolio_value'] = portfolio_value
            info.update(self._calculate_metrics())

        return np.array(padded_state), reward, done, truncated, info

    def reset(self, **kwargs):
        self.portfolio_values = []
        state = self.env.reset(**kwargs)
        state = state[0]  # Only use the list of values from the state tuple

        self.observation_window = deque([state] * self.window_size, maxlen=self.window_size)
        for idx, obs in enumerate(self.observation_window):
            print(f"Initial observation shape at index {idx}: {np.array(obs).shape}")

        return np.array(self.observation_window)

    def _calculate_portfolio_value(self):
        cash = self.env.state[0]
        stocks = np.array(self.env.state[1:self.env.stock_dim + 1])
        holdings = np.array(self.env.state[self.env.stock_dim + 1:2 * self.env.stock_dim + 1])
        return cash + np.sum(stocks * holdings)

    def _calculate_metrics(self):
        if not self.portfolio_values:
            return {}

        portfolio_series = pd.Series(self.portfolio_values)
        daily_returns = portfolio_series.pct_change().dropna()

        sharpe_ratio = np.nan
        if daily_returns.std() != 0:
            sharpe_ratio = (252 ** 0.5) * daily_returns.mean() / daily_returns.std()

        profits = daily_returns[daily_returns > 0]
        losses = daily_returns[daily_returns < 0]

        appt = (profits.sum() + losses.sum()) / len(daily_returns) if len(daily_returns) > 0 else np.nan
        mpb = np.max(portfolio_series)
        mer = daily_returns.mean() - 0.03 / 252
        cr = (portfolio_series.iloc[-1] / portfolio_series.iloc[0]) - 1

        return {
            'Sharpe Ratio': sharpe_ratio,
            'APPT': appt,
            'MPB': mpb,
            'MER': mer,
            'CR': cr
        }

class LSTMFeatureExtractor(BaseFeaturesExtractor):
    def __init__(self, observation_space, hidden_size=128, num_layers=1):
        super(LSTMFeatureExtractor, self).__init__(observation_space, features_dim=hidden_size)
        self.hidden_size = hidden_size
        self.num_layers = num_layers

        self.lstm = None  # Initialize LSTM in the forward method
        self.linear = nn.Sequential(
            nn.Linear(hidden_size, hidden_size),
            nn.ReLU(),
            nn.Linear(hidden_size, hidden_size),
            nn.ReLU(),
            nn.Linear(hidden_size, hidden_size)
        )

    def forward(self, x):
       # print(f"Input shape: {x.shape}")

        # Add sequence length dimension if missing
        if len(x.shape) == 2:
            x = x.unsqueeze(1)  # Add sequence dimension

        if self.lstm is None:
            # Infer input size from the first observation
            input_size = x.shape[2]
            self.lstm = nn.LSTM(input_size=input_size,
                                hidden_size=self.hidden_size,
                                num_layers=self.num_layers,
                                batch_first=True).to(x.device)

        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(x.device)
        c0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(x.device)

        out, (hn, cn) = self.lstm(x, (h0, c0))
        features = hn[-1]  # Take the last hidden state
        return self.linear(features)

policy_kwargs = dict(
    features_extractor_class=LSTMFeatureExtractor,
    features_extractor_kwargs=dict(hidden_size=128, num_layers=1),
)

window_sizes = [5, 15, 30, 50]
results = {}

#### Training loop

In [ ]:

for window_size in window_sizes:
    e_train_gym = StockTradingEnv(df=train, **env_kwargs)
    e_train_env = StockTradingEnvWrapper(e_train_gym, window_size=window_size)

    env_train, _ = e_train_gym.get_sb_env()

    model = RecurrentPPO("MlpLstmPolicy", env_train, policy_kwargs=policy_kwargs, verbose=1)
    model.learn(total_timesteps=5000)

    vec_env = model.get_env()
    mean_reward, std_reward = evaluate_policy(model, vec_env, n_eval_episodes=3, warn=False)
    print(mean_reward)
    # Save the model
    model_path = os.path.join(model_dir, f"ppo_recurrent_window_{window_size}")
    model.save(model_path)
    del model  # Free memory

Using cpu device
----------------------------
| time/              |     |
|    fps             | 117 |
|    iterations      | 1   |
|    time_elapsed    | 1   |
|    total_timesteps | 128 |
----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 31          |
|    iterations           | 2           |
|    time_elapsed         | 8           |
|    total_timesteps      | 256         |
| train/                  |             |
|    approx_kl            | 0.005729061 |
|    clip_fraction        | 0.00781     |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.1        |
|    explained_variance   | -0.0619     |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0101     |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.00866    |
|    std                  | 1           |
|    value_loss           | 0.0388      |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 37          |
|    iterations           | 3           |
|    time_elapsed         | 10          |
|    total_timesteps      | 384         |
| train/                  |             |
|    approx_kl            | 0.008619109 |
|    clip_fraction        | 0.032       |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.1        |
|    explained_variance   | -0.00198    |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0133     |
|    n_updates            | 20          |
|    policy_gradient_loss | -0.00868    |
|    std                  | 1           |
|    value_loss           | 0.0273      |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 42          |
|    iterations           | 4           |
|    time_elapsed         | 12          |
|    total_timesteps      | 512         |
| train/                  |             |
|    approx_kl            | 0.014353013 |
|    clip_fraction        | 0.0633      |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.09       |
|    explained_variance   | 0.0448      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0354     |
|    n_updates            | 30          |
|    policy_gradient_loss | -0.0208     |
|    std                  | 0.999       |
|    value_loss           | 0.00787     |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 46          |
|    iterations           | 5           |
|    time_elapsed         | 13          |
|    total_timesteps      | 640         |
| train/                  |             |
|    approx_kl            | 0.010699619 |
|    clip_fraction        | 0.0414      |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.09       |
|    explained_variance   | 0.0301      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0147     |
|    n_updates            | 40          |
|    policy_gradient_loss | -0.0087     |
|    std                  | 0.999       |
|    value_loss           | 0.000409    |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 49          |
|    iterations           | 6           |
|    time_elapsed         | 15          |
|    total_timesteps      | 768         |
| train/                  |             |
|    approx_kl            | 0.013421817 |
|    clip_fraction        | 0.0563      |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.09       |
|    explained_variance   | -0.000877   |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0187     |
|    n_updates            | 50          |
|    policy_gradient_loss | -0.00898    |
|    std                  | 0.998       |
|    value_loss           | 0.000795    |
-----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 52         |
|    iterations           | 7          |
|    time_elapsed         | 17         |
|    total_timesteps      | 896        |
| train/                  |            |
|    approx_kl            | 0.01513408 |
|    clip_fraction        | 0.0852     |
|    clip_range           | 0.2        |
|    entropy_loss         | -7.09      |
|    explained_variance   | 0.00115    |
|    learning_rate        | 0.0003     |
|    loss                 | -0.0095    |
|    n_updates            | 60         |
|    policy_gradient_loss | -0.00636   |
|    std                  | 0.997      |
|    value_loss           | 0.00657    |
----------------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 54           |
|    iterations           | 8            |
|    time_elapsed         | 18           |
|    total_timesteps      | 1024         |
| train/                  |              |
|    approx_kl            | 0.0061598835 |
|    clip_fraction        | 0.00703      |
|    clip_range           | 0.2          |
|    entropy_loss         | -7.08        |
|    explained_variance   | -0.00325     |
|    learning_rate        | 0.0003       |
|    loss                 | -0.0119      |
|    n_updates            | 70           |
|    policy_gradient_loss | -0.0039      |
|    std                  | 0.997        |
|    value_loss           | 0.00309      |
------------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 55          |
|    iterations           | 9           |
|    time_elapsed         | 20          |
|    total_timesteps      | 1152        |
| train/                  |             |
|    approx_kl            | 0.018614367 |
|    clip_fraction        | 0.0906      |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.08       |
|    explained_variance   | 0.00282     |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0183     |
|    n_updates            | 80          |
|    policy_gradient_loss | -0.012      |
|    std                  | 0.996       |
|    value_loss           | 0.00161     |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 54          |
|    iterations           | 10          |
|    time_elapsed         | 23          |
|    total_timesteps      | 1280        |
| train/                  |             |
|    approx_kl            | 0.008189993 |
|    clip_fraction        | 0.0273      |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.08       |
|    explained_variance   | 0.00425     |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0125     |
|    n_updates            | 90          |
|    policy_gradient_loss | -0.00673    |
|    std                  | 0.996       |
|    value_loss           | 0.00105     |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 55          |
|    iterations           | 11          |
|    time_elapsed         | 25          |
|    total_timesteps      | 1408        |
| train/                  |             |
|    approx_kl            | 0.004575432 |
|    clip_fraction        | 0.00859     |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.08       |
|    explained_variance   | 0.00393     |
|    learning_rate        | 0.0003      |
|    loss                 | -0.00911    |
|    n_updates            | 100         |
|    policy_gradient_loss | -0.00368    |
|    std                  | 0.997       |
|    value_loss           | 0.00158     |
-----------------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 55           |
|    iterations           | 12           |
|    time_elapsed         | 27           |
|    total_timesteps      | 1536         |
| train/                  |              |
|    approx_kl            | 0.0105906725 |
|    clip_fraction        | 0.0336       |
|    clip_range           | 0.2          |
|    entropy_loss         | -7.08        |
|    explained_variance   | 0.00091      |
|    learning_rate        | 0.0003       |
|    loss                 | -0.0136      |
|    n_updates            | 110          |
|    policy_gradient_loss | -0.00768     |
|    std                  | 0.997        |
|    value_loss           | 0.00457      |
------------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 55          |
|    iterations           | 13          |
|    time_elapsed         | 29          |
|    total_timesteps      | 1664        |
| train/                  |             |
|    approx_kl            | 0.004531932 |
|    clip_fraction        | 0.00547     |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.08       |
|    explained_variance   | -0.0185     |
|    learning_rate        | 0.0003      |
|    loss                 | -0.012      |
|    n_updates            | 120         |
|    policy_gradient_loss | -0.00287    |
|    std                  | 0.997       |
|    value_loss           | 0.00297     |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 56          |
|    iterations           | 14          |
|    time_elapsed         | 31          |
|    total_timesteps      | 1792        |
| train/                  |             |
|    approx_kl            | 0.018495962 |
|    clip_fraction        | 0.0836      |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.08       |
|    explained_variance   | -0.000402   |
|    learning_rate        | 0.0003      |
|    loss                 | -0.02       |
|    n_updates            | 130         |
|    policy_gradient_loss | -0.012      |
|    std                  | 0.998       |
|    value_loss           | 0.00346     |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 54          |
|    iterations           | 15          |
|    time_elapsed         | 35          |
|    total_timesteps      | 1920        |
| train/                  |             |
|    approx_kl            | 0.017745048 |
|    clip_fraction        | 0.102       |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.08       |
|    explained_variance   | -0.000309   |
|    learning_rate        | 0.0003      |
|    loss                 | -0.000714   |
|    n_updates            | 140         |
|    policy_gradient_loss | -0.0136     |
|    std                  | 0.997       |
|    value_loss           | 0.0385      |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 53          |
|    iterations           | 16          |
|    time_elapsed         | 38          |
|    total_timesteps      | 2048        |
| train/                  |             |
|    approx_kl            | 0.009518525 |
|    clip_fraction        | 0.0281      |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.08       |
|    explained_variance   | -0.000108   |
|    learning_rate        | 0.0003      |
|    loss                 | 0.0307      |
|    n_updates            | 150         |
|    policy_gradient_loss | -0.0053     |
|    std                  | 0.996       |
|    value_loss           | 0.0888      |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 52          |
|    iterations           | 17          |
|    time_elapsed         | 41          |
|    total_timesteps      | 2176        |
| train/                  |             |
|    approx_kl            | 0.028446678 |
|    clip_fraction        | 0.137       |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.07       |
|    explained_variance   | 0.00372     |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0187     |
|    n_updates            | 160         |
|    policy_gradient_loss | -0.022      |
|    std                  | 0.995       |
|    value_loss           | 0.0233      |
-----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 53         |
|    iterations           | 18         |
|    time_elapsed         | 43         |
|    total_timesteps      | 2304       |
| train/                  |            |
|    approx_kl            | 0.01205655 |
|    clip_fraction        | 0.05       |
|    clip_range           | 0.2        |
|    entropy_loss         | -7.07      |
|    explained_variance   | 0.000801   |
|    learning_rate        | 0.0003     |
|    loss                 | 0.00409    |
|    n_updates            | 170        |
|    policy_gradient_loss | -0.00735   |
|    std                  | 0.993      |
|    value_loss           | 0.0396     |
----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 53          |
|    iterations           | 19          |
|    time_elapsed         | 45          |
|    total_timesteps      | 2432        |
| train/                  |             |
|    approx_kl            | 0.011390241 |
|    clip_fraction        | 0.0336      |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.06       |
|    explained_variance   | -0.000126   |
|    learning_rate        | 0.0003      |
|    loss                 | -0.011      |
|    n_updates            | 180         |
|    policy_gradient_loss | -0.00784    |
|    std                  | 0.992       |
|    value_loss           | 0.0266      |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 54          |
|    iterations           | 20          |
|    time_elapsed         | 46          |
|    total_timesteps      | 2560        |
| train/                  |             |
|    approx_kl            | 0.017989954 |
|    clip_fraction        | 0.0867      |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.05       |
|    explained_variance   | 0.00199     |
|    learning_rate        | 0.0003      |
|    loss                 | 0.0821      |
|    n_updates            | 190         |
|    policy_gradient_loss | -0.0121     |
|    std                  | 0.992       |
|    value_loss           | 0.233       |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 55          |
|    iterations           | 21          |
|    time_elapsed         | 48          |
|    total_timesteps      | 2688        |
| train/                  |             |
|    approx_kl            | 0.013623301 |
|    clip_fraction        | 0.0656      |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.05       |
|    explained_variance   | -0.0209     |
|    learning_rate        | 0.0003      |
|    loss                 | -0.00728    |
|    n_updates            | 200         |
|    policy_gradient_loss | -0.00733    |
|    std                  | 0.991       |
|    value_loss           | 0.0303      |
-----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 56         |
|    iterations           | 22         |
|    time_elapsed         | 50         |
|    total_timesteps      | 2816       |
| train/                  |            |
|    approx_kl            | 0.01620014 |
|    clip_fraction        | 0.0797     |
|    clip_range           | 0.2        |
|    entropy_loss         | -7.05      |
|    explained_variance   | 0.0111     |
|    learning_rate        | 0.0003     |
|    loss                 | 0.0469     |
|    n_updates            | 210        |
|    policy_gradient_loss | -0.007     |
|    std                  | 0.99       |
|    value_loss           | 0.15       |
----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 56          |
|    iterations           | 23          |
|    time_elapsed         | 51          |
|    total_timesteps      | 2944        |
| train/                  |             |
|    approx_kl            | 0.006072999 |
|    clip_fraction        | 0.0109      |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.04       |
|    explained_variance   | 2.53e-05    |
|    learning_rate        | 0.0003      |
|    loss                 | 1.1         |
|    n_updates            | 220         |
|    policy_gradient_loss | -0.007      |
|    std                  | 0.99        |
|    value_loss           | 3.06        |
-----------------------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 56           |
|    iterations           | 24           |
|    time_elapsed         | 54           |
|    total_timesteps      | 3072         |
| train/                  |              |
|    approx_kl            | 0.0062397677 |
|    clip_fraction        | 0.0117       |
|    clip_range           | 0.2          |
|    entropy_loss         | -7.04        |
|    explained_variance   | 0.00183      |
|    learning_rate        | 0.0003       |
|    loss                 | 0.0523       |
|    n_updates            | 230          |
|    policy_gradient_loss | -0.00432     |
|    std                  | 0.99         |
|    value_loss           | 0.142        |
------------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 56         |
|    iterations           | 25         |
|    time_elapsed         | 56         |
|    total_timesteps      | 3200       |
| train/                  |            |
|    approx_kl            | 0.01766624 |
|    clip_fraction        | 0.118      |
|    clip_range           | 0.2        |
|    entropy_loss         | -7.04      |
|    explained_variance   | -0.00013   |
|    learning_rate        | 0.0003     |
|    loss                 | 0.77       |
|    n_updates            | 240        |
|    policy_gradient_loss | -0.0108    |
|    std                  | 0.99       |
|    value_loss           | 1.57       |
----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 56          |
|    iterations           | 26          |
|    time_elapsed         | 58          |
|    total_timesteps      | 3328        |
| train/                  |             |
|    approx_kl            | 0.002960099 |
|    clip_fraction        | 0.000781    |
|    clip_range           | 0.2         |
|    entropy_loss         | -7.04       |
|    explained_variance   | -1.29e-05   |
|    learning_rate        | 0.0003      |
|    loss                 | 2.25        |
|    n_updates            | 250         |

# Evaluation loop

In [ ]:

for window_size in window_sizes:
    print(f"Evaluating model with window size {window_size}")

    # Reload the model
    model_path = os.path.join(model_dir, f"ppo_recurrent_window_{window_size}")
    model = RecurrentPPO.load(model_path)

    # Evaluate on trade dataset
    e_trade_gym = StockTradingEnv(df=trade, **env_kwargs)
    e_trade_env = StockTradingEnvWrapper(e_trade_gym, window_size=window_size)
    e_trade_env, _ = e_trade_env.get_sb_env()


    # Reset the environment
    obs = e_trade_env.reset()
    obs = np.array([obs])  # Ensure the observation is properly batched
    done = False

    portfolio_values = []

    while not done:
        action, _states = model.predict(obs, deterministic=True)
        action = action[0]  # Ensure the action is a 1-dimensional array
        obs, reward, done, truncated, info = e_trade_env.step(action)
        if isinstance(obs, tuple):
            obs = obs[0]  # Extract the list part of the observation
        obs = np.array([obs])  # Ensure the observation is properly batched
        portfolio_values.append(e_trade_env._calculate_portfolio_value())

    results[window_size] = portfolio_values

# Plot the results
import matplotlib.pyplot as plt

plt.figure(figsize=(14, 6))

for window_size, values in results.items():
    dates = trade.index[:len(values)]
    plt.plot(dates, values, label=f'TimeWindow = {window_size}')

plt.xlabel('Date')
plt.ylabel('Return')
plt.legend()
plt.title('Portfolio Returns for Different Time Windows')
plt.show()

Evaluating model with window size 5

RuntimeError: Error(s) in loading state_dict for RecurrentActorCriticPolicy:
	Unexpected key(s) in state_dict: "features_extractor.lstm.weight_ih_l0", "features_extractor.lstm.weight_hh_l0", "features_extractor.lstm.bias_ih_l0", "features_extractor.lstm.bias_hh_l0", "pi_features_extractor.lstm.weight_ih_l0", "pi_features_extractor.lstm.weight_hh_l0", "pi_features_extractor.lstm.bias_ih_l0", "pi_features_extractor.lstm.bias_hh_l0", "vf_features_extractor.lstm.weight_ih_l0", "vf_features_extractor.lstm.weight_hh_l0", "vf_features_extractor.lstm.bias_ih_l0", "vf_features_extractor.lstm.bias_hh_l0".